### ISSUE TITLE
CLIENT : bug mise à l'echelle

### ISSUE THREAD

**Issue by axel-polin** [axel-polin/Papyrus_UI#23]
Il faut que la mise à l'echelle persiste et qu'elle ne concerne qu'une seul image pour l'instant les deux conditions ne peuvent pas être satisfaite en même temps !

**Comment by quentin-piet** [comment]
mise à l'échelle de toutes les images au moment du push dans Area.images en allant chercher les dimensions réelles. Le ratio est conserver durant le zoom.
