### ISSUE TITLE
OPTION Interface: modal scores 

### ISSUE THREAD

**Issue by quentin-piet** [axel-polin/Papyrus_UI#30]
clic sur une image à importer sélectionne également une image sous le moda (Area.selection). Ne pose pas de gros problème de fonctionnement

**Comment by axel-polin** [comment]
Tenter de modifier le style du modal avec un z-index plus grand ??

**Comment by axel-polin** [comment]
Est-ce que c'est mieux avec un z-index à 10 (on peut accéder au modification de l'image aussi) cela va à l'encontre de cette issue mais c'est peut-être plus ergonomique ?
